name: BuoyyEcon
version: '1.0'
main: com.github.buoyy.buoyyecon.BuoyyEcon
softdepend:
  - Vault
api-version: '1.18'
load: STARTUP
commands:
  econ:
    description: One of the main commands. Use to open GUI or use arguments.
    usage: /econ <reload/view>
  dia:
    description: For all things diamond related.
    usage: /dia <withdraw/deposit/set/open/pay>
  gold:
    description: For all things gold related.
    usage: /gold <withdraw/deposit/set/open/pay>
